spring:
  application:
    name: technical-test-api
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: localhost
      port: 28000
      database: auchan-tech-test

server:
  port: 8086